server:
  port: 8080

spring:
  cloud:
    gateway:
      routes:
        - id: book
          uri: https://booklistingtuan.herokuapp.com/
          predicates:
          - Path=/book/**
          filters:
          - StripPrefix=1
        - id: film
          uri: https://filmlistingtuan.herokuapp.com/
          predicates:
          - Path=/film/**
          filters:
          - name: RequestRateLimiter
            args:
              redis-rate-limiter: 
                replenishRate: 1000
                burstCapacity: 2000
                requestedTokens: 1
  redis:
    database: 0
    host: localhost
    port: 6379